"use client";

import { LayoutGrid, SlidersHorizontal, BellRing, FileText, Sparkles } from "lucide-react";
import ProductFeatureCarousel, {
  type ProductFeatureCarouselItem,
} from "@/components/sections/ProductFeatureCarousel";
import {
  PricingMatrixMockup,
  AvailabilityMockup,
  ShareOfSearchMockup,
  ContentComplianceMockup,
  AiReportMockup,
} from "@/app/plataforma/digital-shelf-analytics/DsaDashboardMockups";

const features: ProductFeatureCarouselItem[] = [
  {
    icon: SlidersHorizontal,
    title: "Price monitoring with context, not just numbers",
    descLead: "Detect price changes before they impact your margin.",
    desc: "See how your product prices move across every retailer, compare against competitors and spot unplanned discounts or pricing shifts in real time. The DSA AI engine analyzes patterns and surfaces the most relevant movements so you don't have to check each channel manually.",
    accent: "from-[#FF177B] to-[#c0136a]",
    dot: "#FF177B",
    customVisual: <PricingMatrixMockup locale="en" />,
  },
  {
    icon: LayoutGrid,
    title: "Availability and stockouts under control",
    descLead: "Know which products are out of stock before you lose the sale.",
    desc: "Identify in real time which SKUs are active, out of stock or partially covered at each retailer. Access historical data to understand stockout patterns and receive automated alerts. The AI agent prioritizes which gaps to fix first based on commercial impact.",
    accent: "from-[#4D4A9D] to-[#6366f1]",
    dot: "#4D4A9D",
    customVisual: <AvailabilityMockup locale="en" />,
  },
  {
    icon: BellRing,
    title: "Share of Search: visibility vs. competitors",
    descLead: "Understand who wins shopper attention in each category.",
    desc: "Analyze your product positioning in search results and key categories at each retailer. Compare your presence against competitors on the first page and distinguish organic visibility from paid ads. Ask the AI directly which competitor grew the most and why.",
    accent: "from-[#FF177B] to-[#EC4899]",
    dot: "#FF177B",
    customVisual: <ShareOfSearchMockup locale="en" />,
  },
  {
    icon: FileText,
    title: "Content compliance across every PDP",
    descLead: "Verify your product pages have everything they need to convert.",
    desc: "Evaluate the completeness of images, titles, descriptions, attributes, videos and enhanced content at each retailer. Monitor that brand guidelines are applied consistently and detect which SKUs have the weakest PDPs. Ask the AI which product pages are costing you the most in lost conversion.",
    accent: "from-[#4D4A9D] to-[#6366f1]",
    dot: "#4D4A9D",
    customVisual: <ContentComplianceMockup locale="en" />,
  },
  {
    icon: Sparkles,
    title: "Executive reports generated by AI",
    descLead: "From millions of data points to an actionable summary in seconds.",
    desc: "The DSA AI agent generates automatic executive analyses covering what changed, why it matters and what to do next. Built for QBRs, team meetings or fast decisions. No manual report building needed. Just ask or activate the analysis and get a summary backed by verifiable data from all your channels.",
    accent: "from-[#FF177B] to-[#c0136a]",
    dot: "#FF177B",
    customVisual: <AiReportMockup locale="en" />,
  },
];

export default function UsaDsaCarousel() {
  return (
    <ProductFeatureCarousel
      sectionTitle="Intelligent monitoring: data + AI to act"
      sectionSubtitle="Every DSA feature combines continuous monitoring with an AI layer that transforms signals into concrete answers for your team."
      labels={["", "", "", "", ""]}
      features={features}
    />
  );
}
